version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "update"
    target-branch: "develop"
    groups:
      gomod-packages:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/build"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "update"
    target-branch: "develop"
    groups:
      docker-packages:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "update"
    target-branch: "develop"
    groups:
      gh-actions-packages:
        patterns:
          - "*"
