{{- if .Values.alerting}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-alert-templates
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: connaisseur-core
    {{- include "helm.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "alert_payload_templates/*").AsConfig | nindent 2 }}

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Chart.Name }}-alertconfig
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: connaisseur-core
    {{- include "helm.labels" . | nindent 4 }}
stringData:
  {{- if .Values.alerting}}
  alertconfig.json: |
    {{ mustToJson .Values.alerting | nindent 4 }}
  {{- end }}
{{- end }}
