apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: connaisseur-core
    {{- include "helm.labels" . | nindent 4 }}
data:
  config.yaml: |
    validators:
    {{- range .Values.application.validators -}}
      {{- $validator := deepCopy . -}}
      {{- if eq $validator.type "notaryv1" -}}
        {{- $_ := unset $validator "auth" -}}
      {{- else if eq $validator.type "notaryv2" -}}
      {{- else if eq $validator.type "cosign" -}}
        {{- $_ := unset $validator "cert" -}}
      {{- end }}
    - {{- $validator | toYaml | trim | nindent 6 -}}
    {{- end }}
    policy:
    {{- range $k,$v := .Values.application.policy }}
    - {{- $v | toYaml | trim | nindent 6 -}}
    {{- end }}
