apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: connaisseur-core
    {{- include "helm.labels" . | nindent 4 }}
rules:
- apiGroups: ["*"]
  resources: ["deployments", "pods", "replicationcontrollers", "replicasets", "daemonsets", "statefulsets", "jobs", "cronjobs", "imagepolicies", "mutatingwebhookconfigurations"]
  verbs: ["get"]
{{- if .Values.kubernetes.deployment.podSecurityPolicy }}
{{- if .Values.kubernetes.deployment.podSecurityPolicy.enabled }}
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
    {{- range  .Values.kubernetes.deployment.podSecurityPolicy.name }}
    - {{ . | quote }}
    {{- end }}
{{- end}}
{{- end}}
