apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-serviceaccount
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: connaisseur-core
    {{- include "helm.labels" . | nindent 4 }}
  {{- if and .Values.kubernetes.serviceaccount .Values.kubernetes.serviceaccount.annotations }}
  annotations:
    {{- toYaml .Values.kubernetes.serviceaccount.annotations | nindent 4 }}
  {{- end }}
