apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kubernetes.service.type }}
  ports:
    - port: {{ .Values.kubernetes.service.port }}
      targetPort: 5000
      name: http
  selector:
    app.kubernetes.io/name: {{ include "helm.name" . }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
