name: get-ips-of-service-containers
description: 'Get notary server IP'
outputs:
  notary_ip:
    description: "IP address of the notary instance"
    value: ${{ steps.get_notary_server_ip.outputs.notary_ip }}
runs:
  using: "composite"
  steps:
    - name: Get IP
      id: get_notary_server_ip
      run: |
        NOTARY_CONTAINER=$(docker container ls --no-trunc --format "{{json . }}" | jq ' . | select(.Image|match("notary:server"))')
        NOTARY_CONTAINER_ID=$(echo ${NOTARY_CONTAINER} | jq -r .ID)
        NOTARY_CONTAINER_NETWORK=$(echo ${NOTARY_CONTAINER} | jq -r .Networks)
        NOTARY_SEARCH_PATH=.[0].NetworkSettings.Networks."${NOTARY_CONTAINER_NETWORK}".IPAddress
        NOTARY_IP=$(docker container inspect ${NOTARY_CONTAINER_ID} | jq -r ${NOTARY_SEARCH_PATH})
        echo notary_ip=${NOTARY_IP} >> ${GITHUB_OUTPUT}
      shell: bash
