name: get-ip-of-notary-signer-container
description: 'Get notary-signer IP'
outputs:
  notary_signer_ip:
    description: "IP address of the notary signer instance"
    value: ${{ steps.get_signer_ip.outputs.notary_signer_ip }}
runs:
  using: "composite"
  steps:
    - name: Get notary signer IP
      id: get_signer_ip
      run: |
        NOTARY_CONTAINER=$(docker container ls --no-trunc --format "{{json . }}" | jq ' . | select(.Image|match("notary:signer"))')
        NOTARY_CONTAINER_ID=$(echo ${NOTARY_CONTAINER} | jq -r .ID)
        NOTARY_CONTAINER_NETWORK=$(echo ${NOTARY_CONTAINER} | jq -r .Networks)
        NOTARY_SEARCH_PATH=.[0].NetworkSettings.Networks."${NOTARY_CONTAINER_NETWORK}".IPAddress
        NOTARY_IP=$(docker container inspect ${NOTARY_CONTAINER_ID} | jq -r ${NOTARY_SEARCH_PATH})
        echo notary_signer_ip=${NOTARY_IP} >> ${GITHUB_OUTPUT}
      shell: bash
