name: safety
description: "Run Safety on image"
runs:
  using: "composite"
  steps:
    - name: Install safety
      run: |
        pip3 install safety
      shell: bash
    - name: Run safety
      run: |
        safety check --file requirements.txt --file requirements_dev.txt --full-report -o screen --save-json safety-report.json
      shell: bash
    - name: Upload
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      if: failure()
      with:
        name: safety-report
        path: safety-report.json
