name: nightly

on:
  schedule:
    - cron: "30 1 * * *"

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  ci:
    uses: ./.github/workflows/.reusable-ci.yml
    permissions:
      packages: write
      contents: write
      id-token: write
      security-events: write
      actions: read
      checks: read
      deployments: read
      issues: read
      discussions: read
      pages: read
      pull-requests: read
      repository-projects: read
      statuses: read
    secrets: inherit
    with:
      skip_build: "none"
      skip_compliance_checks: "none"
      skip_unit_tests: "all"
      skip_sast: "all"
      skip_sca: "none"
      skip_docs: "all"
      skip_integration_tests: "all"
      output_type: "table"

  cleanup-registry:
    uses: ./.github/workflows/.reusable-cleanup-registry.yml
    needs: [ci]
    secrets: inherit
