name: pr

permissions: {}

on:
  pull_request:
    branches:
      - master
      - develop

defaults:
  run:
    shell: bash

jobs:
  ci:
    uses: ./.github/workflows/.reusable-ci.yml
    permissions:
      packages: write
      contents: write
      id-token: write
      security-events: write
      actions: read
      checks: read
      deployments: read
      issues: read
      discussions: read
      pages: read
      pull-requests: read
      repository-projects: read
      statuses: read
    secrets: inherit
    with:
      skip_build: 'none'
      skip_compliance_checks: 'none'
      skip_unit_tests: 'none'
      skip_sast: 'none'
      skip_sca: 'none'
      skip_docs: 'none'
      skip_integration_tests: 'none'
      output_type: 'sarif'
