name: publish

permissions: {}

on:
  workflow_dispatch:
    inputs:
      chart_version:
        description: "Version of the connaisseur helm chart to publish"
        type: string

jobs:
  publish:
    uses: ./.github/workflows/.reusable-publish.yml
    permissions:
      contents: write
    with:
      chart_version: ${{ inputs.chart_version }}
